=== pngames/pavillon-noir/branches/2011-port/tags/pavillon-noir-0.0.1/pavillonnoir/__binaries/datafiles/maps/physics_demo_02/model.dtd
<!--
     http://www.pavillon-noir.org/
     XML DTD for object.xml
-->

<!ELEMENT model (listmaterials?, skeleton?, listanims?)>
<!ELEMENT listmaterials (material*)>
<!ELEMENT listanims (anim*)>
<!ELEMENT material EMPTY>
<!ELEMENT skeleton EMPTY>
<!ELEMENT anim EMPTY>

<!ATTLIST model path CDATA #IMPLIED>

<!ATTLIST material path CDATA #REQUIRED>

<!ATTLIST skeleton path CDATA #REQUIRED>

<!ATTLIST anim path CDATA #REQUIRED>

=== pngames/pavillon-noir/pavillonnoir/__doc/dtd/object.xml
<?xml version="1.0"?>
<!DOCTYPE model SYSTEM "model.dtd">
<model path="human.pnm">
  <listmaterials>
    <material path="text_human_1.pnt" />
    <material path="text_human_2.pnt" />
    <material path="text_human_3.pnt" />
  </listmaterials>
  <skeleton path="human.pns" />
  <listanims>
    <anim path="anim_human_1.pna" />
    <anim path="anim_human_2.pna" />
    <anim path="anim_human_3.pna" />
  </listanims>
</model>
