=== pngames/pavillon-noir/pavillonnoir/__binaries/datafiles/maps/entities.dtd
<!--
	http://www.pavillon-noir.org/
	XML DTD for 3D models and scripts (entities.xml)
-->

<!-- HEADER -->

<!ENTITY % object.dtd SYSTEM "../objects/object.dtd">

<!-- ELEMENTS -->

<!ELEMENT entities (entity*, skybox?)>
<!ELEMENT skybox (object?)>
<!ELEMENT entity (script?, object?)>
    <!ELEMENT script (init_code, action_code)>
        <!ELEMENT init_code (#PCDATA)>
        <!ELEMENT action_code (#PCDATA)>

<!-- ENTITIES ATTRIBUTES -->

<!ATTLIST entities mpp CDATA #IMPLIED>

<!-- ENTITY ATTRIBUTES -->

<!ATTLIST entity id ID #REQUIRED>
<!ATTLIST entity label CDATA #IMPLIED>
<!ATTLIST entity mdref CDATA #REQUIRED>
<!ATTLIST entity class CDATA #REQUIRED>
<!ATTLIST entity envtype (dynamic|static|ground) "dynamic">
<!ATTLIST entity objtype (object|dynamic|character) "object">
<!ATTLIST entity x CDATA #REQUIRED>
<!ATTLIST entity y CDATA #REQUIRED>
<!ATTLIST entity z CDATA #REQUIRED>
<!ATTLIST entity xx CDATA #REQUIRED>
<!ATTLIST entity yy CDATA #REQUIRED>
<!ATTLIST entity zz CDATA #REQUIRED>
<!ATTLIST entity ww CDATA #REQUIRED>

<!ATTLIST skybox enabled (true|false) #IMPLIED>
<!ATTLIST skybox top CDATA #IMPLIED>
<!ATTLIST skybox botttom CDATA #IMPLIED>
<!ATTLIST skybox left CDATA #IMPLIED>
<!ATTLIST skybox right CDATA #IMPLIED>
<!ATTLIST skybox front CDATA #IMPLIED>
<!ATTLIST skybox back CDATA #IMPLIED>

<!ATTLIST script type CDATA #IMPLIED>

<!ATTLIST init_code src CDATA #IMPLIED>
<!ATTLIST action_code src CDATA #IMPLIED>


<!-- EXTERNALS -->

%object.dtd;

=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/JiveLevel/entities.xml
<?xml version="1.0"?>
<!DOCTYPE entities SYSTEM "../entities.dtd">
<entities>
<!-- entity id="0" label="Ground" mdref="JiveImportPlan.pno" envtype="static" objtype="object" class="PN3DObject" x="0" y="0" z="0" xx="0" yy="0" zz="-0.008725" ww="0.999809">
</entity -->
<entity id="0" label="Ground" mdref="JiveImportPlan.pno" envtype="static" objtype="object" class="PN3DObject" x="0" y="0" z="0" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="1" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="0" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="2" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="1000" z="100" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="3" label="CollidePave" mdref="JiveImportPave.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="800" z="100" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="4" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="5" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="45" y="650" z="300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="6" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="100" y="600" z="30" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="Player" label="pirate1" mdref="[non-free]pirate.pno" envtype="dynamic" objtype="object" class="PNPlayer" x="-349.293274" y="60.0" z="-161.569168" xx="0.000000" yy="0.000000" zz="0.000000" ww="1.000000">
</entity>
</entities>

=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/physics_dev/entities.xml
<?xml version="1.0"?>
<!DOCTYPE entities SYSTEM "../entities.dtd">
<entities mpp="0.5">
<entity id="id_0" label="Ground" mdref="JiveImportPlan.pno" envtype="static" objtype="object" class="PN3DObject" x="0" y="0" z="0" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_1" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="0" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_2" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="1000" z="100" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_3" label="CollidePave" mdref="JiveImportPave.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="800" z="100" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_4" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_5" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="45" y="650" z="300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_6" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="100" y="600" z="30" xx="0" yy="0" zz="0" ww="1">
</entity>
</entities>

=== pngames/pavillon-noir/pavillonnoir/__binaries/datafiles/free/maps/physics_demo_domino/entities.xml
<?xml version="1.0"?>
<!DOCTYPE entities SYSTEM "../../../entities.dtd">
<entities>
<entity id="id_99" label="plop" mdref="plane_3000x3000.pno" envtype="static" objtype="object" class="" x="1300" y="-2" z="1300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="id_30" label="plop" mdref="cube_60x60x100.pno" envtype="dynamic" objtype="object" class="" x="1350.69" y="7.56104" z="611.767" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_31" label="plop" mdref="cube_60x60x120.pno" envtype="dynamic" objtype="object" class="" x="1397.7" y="8.37671" z="691.333" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_32" label="plop" mdref="cube_60x60x140.pno" envtype="dynamic" objtype="object" class="" x="1492.34" y="7.73828" z="694.72" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_144" label="defaultModel" mdref="cube_60x60x80.pno" envtype="dynamic" objtype="object" class="" x="1256.46" y="8.34985" z="609.108" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_145" label="defaultModel" mdref="cube_60x60x60.pno" envtype="dynamic" objtype="object" class="" x="1211.16" y="7.73315" z="532.946" xx="0" yy="0.484809" zz="0" ww="0.87462">
</entity>
<entity id="id_1" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="60" y="68" z="60" xx="-0.0616281" yy="-0.704416" zz="0.0616287" ww="-0.704416">
</entity>
<entity id="id_3" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="140" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="id_5" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="220" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="id_7" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="300" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="id_9" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="380" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="id_16" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="460" y="68" z="66" xx="0" yy="-0.622515" zz="0" ww="-0.782608">
</entity>
<entity id="id_14" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="540.022" y="68" z="102.675" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_111" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="610" y="68" z="155" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_113" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="670" y="68" z="195" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_116" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="730" y="68" z="235" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_118" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="790" y="68" z="275" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_120" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="850" y="68" z="315" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_122" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="910" y="68" z="355" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_124" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="970" y="68" z="395" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_126" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1030" y="68" z="435" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_128" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1090" y="68" z="475" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_130" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1152.67" y="68" z="517.966" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="id_132" label="610" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1190.11" y="128" z="539.532" xx="0" yy="0.492424" zz="0" ww="0.870356">
</entity>
<entity id="id_133" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1284.77" y="148" z="598.722" xx="0" yy="0.492423" zz="0" ww="0.870356">
</entity>
<entity id="id_134" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1325.65" y="168" z="624.287" xx="0" yy="-0.492423" zz="0" ww="-0.870356">
</entity>
<entity id="id_135" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1354.37" y="168" z="639.142" xx="0" yy="-0.492423" zz="0" ww="-0.870356">
</entity>
<entity id="id_136" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1394.79" y="188" z="662.935" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="id_137" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1220.77" y="128" z="557.329" xx="0" yy="-0.492423" zz="0" ww="-0.870355">
</entity>
<entity id="id_139" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1251.89" y="148" z="579.241" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="id_217" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1422.55" y="188" z="679.002" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="id_218" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1464.17" y="208" z="703.103" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="id_219" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1497.04" y="208" z="722.091" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
</entities>

=== pngames/pavillon-noir/pavillonnoir/__binaries/datafiles/maps/physics_dev/entities.xml
<?xml version="1.0"?>
<!DOCTYPE entities SYSTEM "../entities.dtd">
<entities mpp="0.3">
  <entity id="id_0" label="Ground" mdref="JiveImportPlan.pno" envtype="static" objtype="object" class="PN3DObject" x="0" y="0" z="0" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_1" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="0" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_2" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="1000" z="100" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_3" label="CollidePave" mdref="JiveImportPave.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="800" z="100" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_4" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="0" y="500" z="300" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_5" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67715" y="572.14" z="-30.7497" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_6" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="100" y="600" z="30" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_7" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="17.3555" y="416.593" z="-92.6264" xx="-0.420192" yy="0.709214" zz="0.40909" ww="0.391279">
  </entity>
  <entity id="id_8" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="-71.2091" y="391.919" z="68.919" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_9" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="-53.2648" y="453.644" z="187.284" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_10" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="46.2981" y="471.516" z="125.522" xx="0.413114" yy="-0.369494" zz="0.188267" ww="-0.810781">
  </entity>
  <entity id="id_11" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="-73.5249" y="528.992" z="114.229" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_12" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="63.0847" y="461.836" z="56.2879" xx="0.226159" yy="-0.234194" zz="-0.656813" ww="-0.680149">
  </entity>
  <entity id="id_13" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="120.391" y="452.593" z="-34.2616" xx="-0.385006" yy="0.472162" zz="-0.240578" ww="-0.755617">
  </entity>
  <entity id="id_14" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="-28.8361" y="489.968" z="-55.5319" xx="-0.254159" yy="0.0825812" zz="0.297778" ww="0.916467">
  </entity>
  <entity id="id_15" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="-112.887" y="406.819" z="-27.8034" xx="0.290765" yy="-0.566402" zz="0.223112" ww="-0.73815">
  </entity>
  <entity id="id_16" label="CollideBox" mdref="JiveImportBox_02.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="116.339" y="372.552" z="167.395" xx="0.452497" yy="0.261249" zz="0.42632" ww="-0.738408">
  </entity>
  <entity id="id_17" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="96.5872" y="592.391" z="159.311" xx="0" yy="0" zz="-0.325568" ww="0.945518">
  </entity>
  <entity id="id_18" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67722" y="521.996" z="185.555" xx="-0.431469" yy="-0.583097" zz="0.409449" ww="0.553338">
  </entity>
  <entity id="id_19" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67718" y="542.643" z="62.6547" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_20" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67721" y="435.474" z="138.361" xx="0" yy="0" zz="0" ww="1">
  </entity>
  <entity id="id_21" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67716" y="723.553" z="-14.0353" xx="0" yy="0.382683" zz="0" ww="0.92388">
  </entity>
  <entity id="id_22" label="CollideSphere" mdref="JiveImportSphere.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="8.67719" y="614.417" z="92.1508" xx="0.681998" yy="0" zz="0" ww="-0.731354">
  </entity>
</entities>
