=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/entities.dtd
<!--
	http://www.pavillon-noir.org/
	XML DTD for 3D models and scripts (entities.xml)
-->

<!-- HEADER -->

<!ENTITY % object.dtd SYSTEM "../objects/object.dtd">

<!-- ELEMENTS -->

<!ELEMENT listentities (entity*, skybox?)>
<!ELEMENT entity (action*, object?)>
  <!ELEMENT action (script+)>
    <!ELEMENT script EMPTY>
<!ELEMENT skybox (object?)>

<!-- ATTRIBUTES -->

<!ATTLIST entity id ID #REQUIRED>
<!ATTLIST entity label CDATA #IMPLIED>
<!ATTLIST entity mdref CDATA #REQUIRED>
<!ATTLIST entity class CDATA #REQUIRED>
<!ATTLIST entity envtype (dynamic|static|ground) "dynamic">
<!ATTLIST entity objtype (object|dynamic|character) "object">
<!ATTLIST entity x CDATA #REQUIRED>
<!ATTLIST entity y CDATA #REQUIRED>
<!ATTLIST entity z CDATA #REQUIRED>
<!ATTLIST entity xx CDATA #REQUIRED>
<!ATTLIST entity yy CDATA #REQUIRED>
<!ATTLIST entity zz CDATA #REQUIRED>
<!ATTLIST entity ww CDATA #REQUIRED>
  <!ATTLIST action ref CDATA #REQUIRED>
    <!ATTLIST script ref CDATA #REQUIRED>

<!ATTLIST skybox enabled (true|false) #IMPLIED>

<!ATTLIST skybox top CDATA #IMPLIED>
<!ATTLIST skybox botttom CDATA #IMPLIED>
<!ATTLIST skybox left CDATA #IMPLIED>
<!ATTLIST skybox right CDATA #IMPLIED>
<!ATTLIST skybox front CDATA #IMPLIED>
<!ATTLIST skybox back CDATA #IMPLIED>

<!-- EXTERNALS -->

%object.dtd;

=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/physics_demo_02/entities.xml
<?xml version="1.0"?>
<!DOCTYPE listentities SYSTEM "../entities.dtd">
<listentities>
<entity id="99" label="plop" mdref="plane_3000x3000.pno" envtype="static" objtype="object" class="" x="1300" y="-2" z="1300" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="30" label="plop" mdref="cube_60x60x100.pno" envtype="dynamic" objtype="object" class="" x="1350.69" y="7.56104" z="611.767" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="31" label="plop" mdref="cube_60x60x120.pno" envtype="dynamic" objtype="object" class="" x="1397.7" y="8.37671" z="691.333" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="32" label="plop" mdref="cube_60x60x140.pno" envtype="dynamic" objtype="object" class="" x="1492.34" y="7.73828" z="694.72" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="144" label="defaultModel" mdref="cube_60x60x80.pno" envtype="dynamic" objtype="object" class="" x="1256.46" y="8.34985" z="609.108" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="145" label="defaultModel" mdref="cube_60x60x60.pno" envtype="dynamic" objtype="object" class="" x="1211.16" y="7.73315" z="532.946" xx="0" yy="0.484809" zz="0" ww="0.87462">
</entity>
<entity id="1" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="60" y="68" z="60" xx="-0.0616281" yy="-0.704416" zz="0.0616287" ww="-0.704416">
</entity>
<entity id="3" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="140" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="5" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="220" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="7" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="300" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="9" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="380" y="68" z="60" xx="0" yy="0.707107" zz="0" ww="0.707107">
</entity>
<entity id="16" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="460" y="68" z="66" xx="0" yy="-0.622515" zz="0" ww="-0.782608">
</entity>
<entity id="14" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="540.022" y="68" z="102.675" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="111" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="610" y="68" z="155" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="113" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="670" y="68" z="195" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="116" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="730" y="68" z="235" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="118" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="790" y="68" z="275" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="120" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="850" y="68" z="315" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="122" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="910" y="68" z="355" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="124" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="970" y="68" z="395" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="126" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1030" y="68" z="435" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="128" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1090" y="68" z="475" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="130" label="plop" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1152.67" y="68" z="517.966" xx="0" yy="0.5" zz="0" ww="0.866025">
</entity>
<entity id="132" label="610" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1190.11" y="128" z="539.532" xx="0" yy="0.492424" zz="0" ww="0.870356">
</entity>
<entity id="133" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1284.77" y="148" z="598.722" xx="0" yy="0.492423" zz="0" ww="0.870356">
</entity>
<entity id="134" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1325.65" y="168" z="624.287" xx="0" yy="-0.492423" zz="0" ww="-0.870356">
</entity>
<entity id="135" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1354.37" y="168" z="639.142" xx="0" yy="-0.492423" zz="0" ww="-0.870356">
</entity>
<entity id="136" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1394.79" y="188" z="662.935" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="137" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1220.77" y="128" z="557.329" xx="0" yy="-0.492423" zz="0" ww="-0.870355">
</entity>
<entity id="139" label="defaultModel" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="" x="1251.89" y="148" z="579.241" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="217" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1422.55" y="188" z="679.002" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="218" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1464.17" y="208" z="703.103" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
<entity id="219" label="New Object" mdref="domino_uncentered.pno" envtype="dynamic" objtype="object" class="PN3DObject" x="1497.04" y="208" z="722.091" xx="0" yy="0.507538" zz="0" ww="0.861629">
</entity>
</listentities>

=== pngames/pavillon-noir/tags/pavillon-noir-0.0.1/pavillonnoir/__binaries/datafiles/maps/MartiLevel/entities.xml
<?xml version="1.0"?>
<!DOCTYPE entities SYSTEM "entities.dtd">
<listentities>
<entity id="3" label="ground" mdref="carre_texture.pno" envtype="ground" objtype="object" class="PN3DObject" x="-25.0631" y="-101.614" z="-6.23442" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="2" label="cube" mdref="carre_texture.pno" envtype="static" objtype="object" class="PN3DObject" x="62.9448" y="14.0349" z="-40.3354" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="4" label="SkyBoite" mdref="skybox_poor.pno" envtype="static" objtype="object" class="PN3DObject" x="56.65" y="-245.789" z="-34.3423" xx="0" yy="0" zz="0" ww="1">
</entity>
<entity id="1" label="Mecton" mdref="Mecton.pno" envtype="dynamic" objtype="character" class="PN3DSkeletonObject" x="32.8376" y="-151.968" z="-161.339" xx="0" yy="0" zz="0" ww="1">
<action ref="PN_EVENT_GAME_PAUSE">
<script ref="script_9.lua"/>
</action>
<action ref="PN_EVENT_COLLISION">
<script ref="script_1.lua"/>
<script ref="script_2.lua"/>
</action>
</entity>
<entity id="4" label="Fred" mdref="3ddynobject.pno" envtype="dynamic" objtype="dynamic" class="PN3DSkeletonObject" x="-2.85464" y="10.8192" z="-6.7865" xx="0" yy="0" zz="0" ww="1">
</entity>
</listentities>
