=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/waypoints.dtd
<!-- 
     http://www.pavillon-noir.org/
     XML DTD for waypoints.xml
-->

<!ELEMENT graph (listlnk, listwp)>
<!ELEMENT listwp (wp*)>
<!ELEMENT listlnk (lnk*)>
<!ELEMENT wp EMPTY>
<!ELEMENT lnk EMPTY>

<!ATTLIST wp id ID #REQUIRED>
<!ATTLIST wp x CDATA #REQUIRED>
<!ATTLIST wp y CDATA #REQUIRED>
<!ATTLIST wp z CDATA #REQUIRED>

<!ATTLIST lnk from IDREF #REQUIRED>
<!ATTLIST lnk to IDREF #REQUIRED>
<!ATTLIST lnk coef CDATA #REQUIRED>

=== pngames/pavillon-noir/pavillonnoir/__binaries/datafiles/maps/Frustrum_Test_01/waypoints.xml
<?xml version="1.0"?>
<!DOCTYPE graph SYSTEM "../waypoints.dtd">
<graph>
<listwp>
<wp id="id_1" x="1" y="40" z="50"/>
<wp id="id_2" x="0" y="40" z="500"/>
<wp id="id_3" x="-1000" y="40" z="500"/>
<wp id="id_4" x="-1000" y="40" z="-1500"/>
</listwp>
<listlnk>
<lnk from="1" to="2" coef="1"/>
<lnk from="2" to="1" coef="1"/>
<lnk from="2" to="3" coef="1"/>
<lnk from="3" to="2" coef="1"/>
<lnk from="3" to="4" coef="1"/>
<lnk from="4" to="3" coef="1"/>
</listlnk>
</graph>

=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/PF_Test_02/waypoints.xml
<?xml version="1.0"?>
<!DOCTYPE graph SYSTEM "waypoints.dtd">
<graph>
<listwp>
<wp id="1" x="1600.42" y="0" z="3700.98"/>
<wp id="2" x="-4900" y="0" z="0"/>
<wp id="3" x="-4800" y="0" z="-4800"/>
<wp id="4" x="4900" y="0" z="0"/>
<wp id="5" x="4900" y="0" z="4900"/>
<wp id="6" x="-165.88" y="0.809814" z="-3700"/>
<wp id="7" x="4500" y="0" z="-4500"/>
<wp id="8" x="0" y="0" z="0"/>
</listwp>
<listlnk>
<lnk from="1" to="2" coef="1"/>
<lnk from="1" to="4" coef="1"/>
<lnk from="1" to="6" coef="1"/>
<lnk from="1" to="8" coef="1"/>
<lnk from="2" to="1" coef="1"/>
<lnk from="2" to="3" coef="1"/>
<lnk from="3" to="2" coef="1"/>
<lnk from="3" to="6" coef="1"/>
<lnk from="3" to="8" coef="1"/>
<lnk from="4" to="1" coef="1"/>
<lnk from="5" to="8" coef="1"/>
<lnk from="5" to="7" coef="1"/>
<lnk from="6" to="1" coef="1"/>
<lnk from="6" to="3" coef="1"/>
<lnk from="6" to="7" coef="1"/>
<lnk from="7" to="6" coef="1"/>
<lnk from="7" to="5" coef="1"/>
<lnk from="8" to="3" coef="1"/>
<lnk from="8" to="1" coef="1"/>
</listlnk>
</graph>

=== pngames/pavillon-noir/tags/pavillon-noir-0.0.1/pavillonnoir/__binaries/datafiles/maps/MartiLevel/waypoints.xml
<?xml version="1.0"?>
<!DOCTYPE graph SYSTEM "waypoints.dtd">
<graph>
<listwp>
<wp id="8" x="37.6147" y="201.37" z="-89.9059"/>
<wp id="9" x="83.6971" y="40.1792" z="-47.9067"/>
<wp id="10" x="-5.87117" y="-69.2491" z="-25.7303"/>
<wp id="11" x="-1.04158" y="65.2657" z="-108.622"/>
</listwp>
<listlnk>
<lnk from="8" to="9" coef="1"/>
<lnk from="8" to="10" coef="1"/>
<lnk from="9" to="8" coef="1"/>
<lnk from="9" to="10" coef="1"/>
<lnk from="9" to="11" coef="1"/>
<lnk from="10" to="9" coef="1"/>
<lnk from="10" to="11" coef="3"/>
<lnk from="11" to="8" coef="1"/>
<lnk from="11" to="10" coef="3"/>
</listlnk>
</graph>

=== pngames/pavillon-noir/trunk/pavillonnoir/__binaries/datafiles/maps/PF_Test_03/waypoints.xml
<?xml version="1.0"?>
<!DOCTYPE graph SYSTEM "../waypoints.dtd">
<graph>
<listwp>
<wp id="id:1" x="1" y="40" z="50"/>
<wp id="id:2" x="0" y="40" z="500"/>
<wp id="id:3" x="-1000" y="40" z="500"/>
<wp id="id:4" x="-1000" y="40" z="-1500"/>
</listwp>
<listlnk>
<lnk from="1" to="2" coef="1"/>
<lnk from="2" to="1" coef="1"/>
<lnk from="2" to="3" coef="1"/>
<lnk from="3" to="2" coef="1"/>
<lnk from="3" to="4" coef="1"/>
<lnk from="4" to="3" coef="1"/>
</listlnk>
</graph>
